// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadChatLog(arg1) {
  return window['go']['main']['App']['LoadChatLog'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function StartChatWatch(arg1) {
  return window['go']['main']['App']['StartChatWatch'](arg1);
}

export function StopChatWatch() {
  return window['go']['main']['App']['StopChatWatch']();
}
