// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {chatlog} from '../models';

export function GetActiveSessions():Promise<Array<string>>;

export function GetDataDir():Promise<string>;

export function GetGroup(arg1:string):Promise<main.GroupDTO>;

export function ListGroups():Promise<Array<main.GroupDTO>>;

export function ListSessions():Promise<Array<main.SessionDTO>>;

export function LoadChatLog(arg1:string):Promise<Array<chatlog.ChatEvent>>;

export function LoadConfig():Promise<main.ConfigDTO>;

export function LoadSettings():Promise<main.SettingsDTO>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function SaveSettings(arg1:main.SettingsDTO):Promise<void>;

export function SetDataDir(arg1:string):Promise<void>;

export function StartChatWatch(arg1:string):Promise<void>;

export function StartGroupWatch(arg1:string,arg2:number):Promise<void>;

export function StopChatWatch():Promise<void>;

export function StopGroupWatch():Promise<void>;
